---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tusimple-eks-simulation
  region: us-east-1
  version: '1.24'
  tags:
    karpenter.sh/discovery: tusimple-eks-simulation
iam:
  withOIDC: true
  
fargateProfiles:
  - name: system
    selectors:
      - namespace: kube-system
      - namespace: karpenter
karpenter:
  version: 'v0.25.0'
  createServiceAccount: true
  
cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
  
managedNodeGroups:
  - name: al2-private-mng
    instanceType: t3.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    privateNetworking: true 